// Layout tastiera MacBook. Ogni tasto: { code, label, w? (unita' di larghezza),
// tall? (Invio ISO), untestable? }. `code` e' KeyboardEvent.code.

const FN_ROW = [
  { code: 'Escape', label: 'esc', w: 1.4 },
  { code: 'F1', label: 'F1' },
  { code: 'F2', label: 'F2' },
  { code: 'F3', label: 'F3' },
  { code: 'F4', label: 'F4' },
  { code: 'F5', label: 'F5' },
  { code: 'F6', label: 'F6' },
  { code: 'F7', label: 'F7' },
  { code: 'F8', label: 'F8' },
  { code: 'F9', label: 'F9' },
  { code: 'F10', label: 'F10' },
  { code: 'F11', label: 'F11' },
  { code: 'F12', label: 'F12' },
  { code: 'Power', label: '⏻ / Touch ID', w: 1.4, untestable: true },
];

const ARROWS_INLINE = [
  { code: 'ArrowLeft', label: '◀' },
  { code: 'ArrowUp', label: '▲ / ▼', stackArrows: true },
  { code: 'ArrowRight', label: '▶' },
];

export const LAYOUTS = {
  'iso-it': {
    label: 'ISO Italiano',
    rows: [
      FN_ROW,
      [
        { code: 'Backquote', label: '\\ |' },
        { code: 'Digit1', label: '1 !' },
        { code: 'Digit2', label: '2 "' },
        { code: 'Digit3', label: '3 £' },
        { code: 'Digit4', label: '4 $' },
        { code: 'Digit5', label: '5 %' },
        { code: 'Digit6', label: '6 &' },
        { code: 'Digit7', label: '7 /' },
        { code: 'Digit8', label: '8 (' },
        { code: 'Digit9', label: '9 )' },
        { code: 'Digit0', label: '0 =' },
        { code: 'Minus', label: "' ?" },
        { code: 'Equal', label: 'ì ^' },
        { code: 'Backspace', label: '⌫', w: 1.6 },
      ],
      [
        { code: 'Tab', label: '⇥', w: 1.6 },
        { code: 'KeyQ', label: 'Q' },
        { code: 'KeyW', label: 'W' },
        { code: 'KeyE', label: 'E' },
        { code: 'KeyR', label: 'R' },
        { code: 'KeyT', label: 'T' },
        { code: 'KeyY', label: 'Y' },
        { code: 'KeyU', label: 'U' },
        { code: 'KeyI', label: 'I' },
        { code: 'KeyO', label: 'O' },
        { code: 'KeyP', label: 'P' },
        { code: 'BracketLeft', label: 'è é' },
        { code: 'BracketRight', label: '+ *' },
        { code: 'Enter', label: '⏎', tall: true, w: 1.3 },
      ],
      [
        { code: 'CapsLock', label: '⇪', w: 1.8 },
        { code: 'KeyA', label: 'A' },
        { code: 'KeyS', label: 'S' },
        { code: 'KeyD', label: 'D' },
        { code: 'KeyF', label: 'F' },
        { code: 'KeyG', label: 'G' },
        { code: 'KeyH', label: 'H' },
        { code: 'KeyJ', label: 'J' },
        { code: 'KeyK', label: 'K' },
        { code: 'KeyL', label: 'L' },
        { code: 'Semicolon', label: 'ò ç' },
        { code: 'Quote', label: 'à °' },
        { code: 'Backslash', label: 'ù §' },
      ],
      [
        { code: 'ShiftLeft', label: '⇧', w: 1.3 },
        { code: 'IntlBackslash', label: '< >' },
        { code: 'KeyZ', label: 'Z' },
        { code: 'KeyX', label: 'X' },
        { code: 'KeyC', label: 'C' },
        { code: 'KeyV', label: 'V' },
        { code: 'KeyB', label: 'B' },
        { code: 'KeyN', label: 'N' },
        { code: 'KeyM', label: 'M' },
        { code: 'Comma', label: ', ;' },
        { code: 'Period', label: '. :' },
        { code: 'Slash', label: '- _' },
        { code: 'ShiftRight', label: '⇧', w: 2.3 },
      ],
      [
        { code: 'Fn', label: 'fn / 🌐', untestable: true },
        { code: 'ControlLeft', label: '⌃' },
        { code: 'AltLeft', label: '⌥' },
        { code: 'MetaLeft', label: '⌘', w: 1.3 },
        { code: 'Space', label: '', w: 5 },
        { code: 'MetaRight', label: '⌘', w: 1.3 },
        { code: 'AltRight', label: '⌥' },
        ...ARROWS_INLINE,
      ],
    ],
  },

  'ansi-us': {
    label: 'ANSI US',
    rows: [
      FN_ROW,
      [
        { code: 'Backquote', label: '` ~' },
        { code: 'Digit1', label: '1 !' },
        { code: 'Digit2', label: '2 @' },
        { code: 'Digit3', label: '3 #' },
        { code: 'Digit4', label: '4 $' },
        { code: 'Digit5', label: '5 %' },
        { code: 'Digit6', label: '6 ^' },
        { code: 'Digit7', label: '7 &' },
        { code: 'Digit8', label: '8 *' },
        { code: 'Digit9', label: '9 (' },
        { code: 'Digit0', label: '0 )' },
        { code: 'Minus', label: '- _' },
        { code: 'Equal', label: '= +' },
        { code: 'Backspace', label: '⌫', w: 1.6 },
      ],
      [
        { code: 'Tab', label: '⇥', w: 1.6 },
        { code: 'KeyQ', label: 'Q' },
        { code: 'KeyW', label: 'W' },
        { code: 'KeyE', label: 'E' },
        { code: 'KeyR', label: 'R' },
        { code: 'KeyT', label: 'T' },
        { code: 'KeyY', label: 'Y' },
        { code: 'KeyU', label: 'U' },
        { code: 'KeyI', label: 'I' },
        { code: 'KeyO', label: 'O' },
        { code: 'KeyP', label: 'P' },
        { code: 'BracketLeft', label: '[ {' },
        { code: 'BracketRight', label: '] }' },
        { code: 'Backslash', label: '\\ |', w: 1.4 },
      ],
      [
        { code: 'CapsLock', label: '⇪', w: 1.8 },
        { code: 'KeyA', label: 'A' },
        { code: 'KeyS', label: 'S' },
        { code: 'KeyD', label: 'D' },
        { code: 'KeyF', label: 'F' },
        { code: 'KeyG', label: 'G' },
        { code: 'KeyH', label: 'H' },
        { code: 'KeyJ', label: 'J' },
        { code: 'KeyK', label: 'K' },
        { code: 'KeyL', label: 'L' },
        { code: 'Semicolon', label: '; :' },
        { code: 'Quote', label: "' \"" },
        { code: 'Enter', label: '⏎', w: 1.9 },
      ],
      [
        { code: 'ShiftLeft', label: '⇧', w: 2.4 },
        { code: 'KeyZ', label: 'Z' },
        { code: 'KeyX', label: 'X' },
        { code: 'KeyC', label: 'C' },
        { code: 'KeyV', label: 'V' },
        { code: 'KeyB', label: 'B' },
        { code: 'KeyN', label: 'N' },
        { code: 'KeyM', label: 'M' },
        { code: 'Comma', label: ', <' },
        { code: 'Period', label: '. >' },
        { code: 'Slash', label: '/ ?' },
        { code: 'ShiftRight', label: '⇧', w: 2.4 },
      ],
      [
        { code: 'Fn', label: 'fn / 🌐', untestable: true },
        { code: 'ControlLeft', label: '⌃' },
        { code: 'AltLeft', label: '⌥' },
        { code: 'MetaLeft', label: '⌘', w: 1.3 },
        { code: 'Space', label: '', w: 5 },
        { code: 'MetaRight', label: '⌘', w: 1.3 },
        { code: 'AltRight', label: '⌥' },
        ...ARROWS_INLINE,
      ],
    ],
  },
};

export function testableCodes(layoutKey) {
  const set = new Set();
  for (const row of LAYOUTS[layoutKey].rows) {
    for (const key of row) {
      if (key.untestable) continue;
      set.add(key.code);
      if (key.stackArrows) set.add('ArrowDown');
    }
  }
  return set;
}
